cherry:
  connectorslib:
    uploadpath: ./localstorage/upload
    classloaderpath: ./localstorage/classloader
    forcerefresh: true

  runners:
    # the runtime load all embedded runners
    embeddedrunner: true

    # the runtime load ping runners
    pingrunner: false


# Visit https://github.com/camunda-community-hub/spring-zeebe/?tab=readme-ov-file#connect-to-zeebe

# -------------------- Self Manage
camunda:
  client:
    mode: simple
    zeebe:
      enabled: true
      gatewayUrl: http://localhost:26500
      preferRestOverGrpc: false
      executionThreads: 200
      defaults:
        maxJobsActive: 58
    operate:
      enabled: false
    tasklist:
      enabled: false

# -------------------- Self Manage Identity
camundaIdentity:
  client:
    mode: oidc
    auth:
      clientId: zeebe
      clientSecret: 6DOXVAFyoC

    zeebe:
      enabled: true
      gatewayUrl: http://localhost:26500
      preferRestOverGrpc: false
      audience: zeebe-api

    operate:
      enabled: false
    tasklist:
      enabled: false


# -------------------- SAAS
camundaSaas:
  client:
    mode: saas
    auth:
      clientId: Lu.lVob..
      clientSecret: aoO.....
    clusterId: b16d70..
    region: jfk-1



server.port: 9081
logging.level.root: INFO


# return message with BAD_REQUEST to the client
server.error.include-message: always

# Spring Boot Configuration
spring.application.name: CherryRuntime

# Cherry will override the zeebeClient bean
spring:
  main:
    allow-bean-definition-overriding: true

# --------------------- H2 - default
spring.datasource:
  url: "jdbc:h2:file:./cherry.db"
  driver-class-name: "org.h2.Driver"
  username: "sa"
  password: "password"
spring.jpa.database-platform: "org.hibernate.dialect.H2Dialect"
org.hibernate.dialect: "H2Dialect"


# --------------------- Postgres
springPostgresexample.datasource:
  url: "jdbc:postgresql://localhost/cherrydb"
  username: "camunda"
  password: "camunda"
  driverClassName: "org.postgresql.Driver"
spring2.jpa.database-platform: "org.hibernate.dialect.PostgreSQL94Dialect"

orgPostgres.hibernate.dialect: "PostgreSQL94Dialect"



# allow CLOB in Postgres
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true




spring.jpa:
  generate-ddl: true
  hibernate.ddl-auto: "update"

  properties:
    hibernate:
      format_sql: true
      show-sql: true


# logging.level.org.hibernate.SQL: TRACE
# logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE
# logging.level.org.hibernate.postgresql : TRACE
# spring.jpa.properties.hibernate.show_sql: true
# spring.jpa.properties.hibernate.use_sql_comments: true
# spring.jpa.properties.hibernate.format_sql: true

