apiVersion: apps/v1
kind: Deployment
metadata:
  name: cherry-runtime-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cherry-runtime
  template:
    metadata:
      labels:
        app: cherry-runtime
    spec:
      containers:
        - name: cherry-runtime-container
          image: ghcr.io/camunda-community-hub/zeebe-cherry-runtime:latest
          ports:
            - containerPort: 8080
          env:
            - name: CHERRY_CONNECTORSLIB_UPLOADPATH
              value: /usr/local/cherry/upload
            - name:  CHERRY_CONNECTORSLIB_CLASSLOADERPATH
              value: /usr/localstorage/classloader
            - name: CAMUNDA_CLIENT_ZEEBE_GATEWAY-URL
              value: http://camunda-zeebe-gateway:26500
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://cherry-postgres/cherrydb"
            - name: SPRING_DATASOURCE_USERNAME
              value: "cherryUser"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "cherryPassword"
            - name: SPRING_DATASOURCE_DRIVER-CLASS-NAME
              value: "org.postgresql.Driver"
            - name: "JPA_DATABASE-PLATFORM"
              value: "org.hibernate.dialect.PostgreSQLDialect"
---
apiVersion: v1
kind: Service
metadata:
  name: cherry-runtime-service
spec:
  selector:
    app: cherry-runtime
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cherry-postgres
spec:
  serviceName: "cherry-postgres"
  replicas: 1
  selector:
    matchLabels:
      app: cherry-postgres
  template:
    metadata:
      labels:
        app: cherry-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: mydatabase
            - name: POSTGRES_USER
              value: "cherryUser"
            - name: POSTGRES_PASSWORD
              value: "cherryPassword"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "standard"  # Replace with your storage class name if different
        resources:
          requests:
            storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: cherry-postgres-svc
spec:
  selector:
    app: cherry-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
