apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        importer: cherry-runtime
        app: camunda-platform
        app.kubernetes.io/component: cherry-runtime
    spec:
      containers:
        - env:
            - name: CHERRY_CONNECTORSLIB_UPLOADPATH
              value: /usr/local/cherry/upload
            - name:  CHERRY_CONNECTORSLIB_CLASSLOADERPATH
              value: /usr/localstorage/classloader
            - name: CAMUNDA_CLIENT_ZEEBE_GATEWAY-URL
              value: http://camunda-zeebe-gateway:26500
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://cherry-postgres/cherrydb"
            - name: SPRING_DATASOURCE_USERVNAME
              value: "camunda"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "camunda"
            - name: SPRING_DATASOURCE_DRIVER-CLASS-NAME
              value: "org.postgresql.Driver"
            - name: "JPA_DATABASE-PLATFORM"
              value: "org.hibernate.dialect.PostgreSQLDialect"

          image: ghcr.io/camunda-community-hub/zeebe-cherry-runtime:latest
          imagePullPolicy: IfNotPresent
          name: cherry-runtime
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 100mb
            requests:
              cpu: "1"
              memory: 100mb
          volumeMounts:
            - mountPath: /usr/local/cherry/upload
              name: upload
            - mountPath: /usr/local/cherry/classloader
              name: classloader
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
        runAsNonRoot: true
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: upload
        - emptyDir: {}
          name: classloader
  selector:
    matchLabels:
      importer: cherry-runtime
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: cherry
            - name: POSTGRES_USER
              value: camunda
            - name: POSTGRES_PASSWORD
              value: camunda
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
