
services:
  cherryruntime:
    image: ghcr.io/camunda-community-hub/zeebe-cherry-runtime:latest
    container_name: cherryruntime
    ports:
      - "9081:9081"
    environment:
      - ZEEBE_CLIENT_BROKER_GATEWAY_ADDRESS=zeebe:26500
      - ZEEBE_CLIENT_SECURITY_PLAINTEXT=true
#      - ZEEBE_CLIENT_CLOUD_REGION=
#      - ZEEBE_CLIENT_CLOUD_CLUSTERID=
#      - ZEEBE_CLIENT_CLOUD_CLIENTID=
#      - ZEEBE_CLIENT_CLOUD_CLIENTSECRET=
      - LOGGING_LEVEL_ROOT=INFO
    networks:
      - camunda-platform
    depends_on:
      - zeebe

networks:
  camunda-platform:
